name: kaelo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+4

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  go_router: ^16.0.0
  flutter_native_splash: ^2.4.6
  flutter_svg: ^2.2.0
  flutter_localizations:
    sdk: flutter
  localization: ^2.1.1
  flutter_tts: ^4.2.3
  animate_do: ^4.2.0
  flutter_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.3
  http: ^1.5.0
  connectivity_plus: ^7.0.0
  path_provider: ^2.1.5
  audioplayers: ^6.5.1
  crypto: ^3.0.6
  in_app_purchase: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - lib/i18n/

